---
- name: installing apache
  hosts: all
  become: yes
  tasks:
    - name: installing apache
      ansible.builtin.apt:
        name: 
          - mysql-server
        update_cache: yes
        state: latest
        # add this tinfo
        