---
- name: installing lamp on redhat 
  hosts: redhathosts 
  become: yes 
  tasks: 
    - name: installing apache 
      ansible.builtin.yum:
        name: httpd
        state: present 
    - name: enabled and start service apache
      ansible.builtin.service: 
        name: httpd
        enabled: yes
        state: started          
    - name: Installing php 
      ansible.builtin.yum:
        name: 
          - php 
        state: present 
      notify:
        - restart service apache
    - name: copy content 
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
      notify:
        - restart service apache
  handlers:
    - name: restart service apache
      ansible.builtin.service:
        name: httpd
        state: restarted
    
    
        
      
         