---
- name: installing lamp on ubuntu 
  hosts: all 
  become: yes 
  tasks: 
    - name: installing apache 
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present 
          
    - name: Installing php 
      ansible.builtin.apt:
        name: 
          - php 
          - libapache2-mod-php 
          - php-mysql  
        state: present 
    - name: copy content 
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php 
    - name: restart service apache
      ansible.builtin.service:
        name: httpd
        state: restarted
        
      
         