---
- name: installing Dotnet-7
  hosts: all
  become: yes
  tasks:
    - name: installing Dotnet-7
      ansible.builtin.apt:
        name: dotnet-sdk=7.0
        update_cache: yes
        state: present
    