---
- name: installing apache
  hosts: all
  become: yes
  tasks:
    - name: installing apache
      ansible.builtin.apt:
        name: 
          - nginx
        update_cache: yes
        state: present
